CREATE DATABASE SUPERMERCADO;
USE SUPERMERCADO;
CREATE TABLE VENDAS(
id INT AUTO_INCREMENT PRIMARY KEY,
PRODUTO VARCHAR (100),
QUANTIDADE INT,
DATA_VENDA DATE);
INSERT INTO VENDAS(PRODUTO, QUANTIDADE, DATA_VENDA) VALUES
('Arroz', 10, '2024-09-01'), ('Feijão', 8, '2024-09-01'), ('Arroz', 15, '2024-09-02'), ('Macarrão', 20, '2024-09-03'), ('Feijão',
12, '2024-09-03'), ('Arroz', 7, '2024-09-04'), ('Macarrão', 30, '2024-09-04');

/*QUANTOS PRODUTOS DE CADA TIPO FORAM VENDIDOS NO TOTAL*/
SELECT PRODUTO, SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS
GROUP BY PRODUTO;

/*QUANTAS VENDAS FORAM FEITAS DE CADA PRODUTO*/
SELECT QUANTIDADE, SUM(PRODUTO) AS TOTAL
FROM VENDAS 
GROUP BY QUANTIDADE;


/*QUANTOS PRODUTOS FORAM VENDIDOS EM CADA DATA*/
SELECT PRODUTO, SUM(QUANTIDADE) AS VENDA_DATA
FROM VENDAS
GROUP BY PRODUTO;