CREATE DATABASE SUPERMERCADO;
USE SUPERMERCADO;
CREATE TABLE PRODUTOS(
id_produtos INT,
nome_produtos VARCHAR(30),
id_fornecedor INT,
preço DECIMAL
);

INSERT INTO PRODUTOS VALUES
(1,'ARROZ',1,25.00),(2, 'fEIJÃO',2,8.50),(3, 'MACARRÃO', 1, 4.00), (4, 'ÓREO',3,6.20), (5, 'AÇÚCAR', 2, 3.50);

CREATE TABLE FORNECEDORES(
id_fornecedor INT,
nome_fornecedor VARCHAR (100)
);

SELECT*FROM PRODUTOS;

INSERT INTO  FORNECEDORES VALUES
(1,'FORNECEDOR A'), (2,'FORNECEDOR B'), (3,'FORNECEDOR C');



ALTER TABLE PRODUTOS MODIFY COLUMN PREÇO INT;
SELECT*FROM PRODUTOS WHERE NOME_PRODUTOS ='ARROZ';
 DROP DATABASE SUPERMERCADO;

