CREATE DATABASE JOIAS;
USE JOIAS;
CREATE TABLE CLIENTES(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
EMAIL VARCHAR(50),
TELEFONE INT
);
INSERT INTO CLIENTES (ID_CLIENTE, NOME, EMAIL, TELEFONE) VALUES
(1, 'Lucas Almeida', 'lucas.almeida@email.com', 12456789),
(2,'MARIANA COSTA', 'mariana.costa@email.com', 456321),
(3,'PABLO ROBERTO', 'paulo.roberto@email.com', 654123);

SELECT * FROM CLIENTES;
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE) VALUES ("FELIPE", "felipe@gmail.com",99999999);


